/* e1a15a0dbb0050b3b56229b75c24432324cdf0cd
 * This file is automatically generated by graphql-let. */

import * as Apollo from '@apollo/client';
export declare type Maybe<T> = T | null;
export declare type Exact<T extends {
    [key: string]: unknown;
}> = {
    [K in keyof T]: T[K];
};
export declare type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]?: Maybe<T[SubKey]>;
};
export declare type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]: Maybe<T[SubKey]>;
};
/** All built-in and custom scalars, mapped to their actual values */
export declare type Scalars = {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
    /** Mongo id scalar type */
    ObjectId: any;
};
export declare type LoginInput = {
    email: Scalars['String'];
    password: Scalars['String'];
};
export declare type Mutation = {
    __typename?: 'Mutation';
    createVoc: Vokabel;
    deleteVok: Scalars['Boolean'];
    login: UserResponse;
    register: UserResponse;
    udpateVok: Vokabel;
};
export declare type MutationCreateVocArgs = {
    input: VokabelInput;
};
export declare type MutationDeleteVokArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type MutationLoginArgs = {
    input: LoginInput;
};
export declare type MutationRegisterArgs = {
    input: RegisterInput;
};
export declare type MutationUdpateVokArgs = {
    input: VokabelInput;
};
export declare type Query = {
    __typename?: 'Query';
    getLoggedUser?: Maybe<User>;
    readUserVoks: Array<Vokabel>;
    readVoc: Vokabel;
    readVocs: Array<Vokabel>;
    user?: Maybe<User>;
};
export declare type QueryReadUserVoksArgs = {
    userId: Scalars['ObjectId'];
};
export declare type QueryReadVocArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type QueryUserArgs = {
    userId: Scalars['ObjectId'];
};
export declare type RegisterInput = {
    email: Scalars['String'];
    password: Scalars['String'];
    username: Scalars['String'];
};
/** User */
export declare type User = {
    __typename?: 'User';
    _id: Scalars['ObjectId'];
    email: Scalars['String'];
    username: Scalars['String'];
};
export declare type UserResponse = {
    __typename?: 'UserResponse';
    token?: Maybe<Scalars['String']>;
    user?: Maybe<User>;
};
/** Vokabel */
export declare type Vokabel = {
    __typename?: 'Vokabel';
    _id: Scalars['ObjectId'];
    creator: User;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type VokabelInput = {
    _id?: Maybe<Scalars['ObjectId']>;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type Delete_VokMutationVariables = Exact<{
    vokId: Scalars['ObjectId'];
}>;
export declare type Delete_VokMutation = ({
    __typename?: 'Mutation';
} & Pick<Mutation, 'deleteVok'>);
export declare const Delete_VokDocument: Apollo.DocumentNode;
export declare type Delete_VokMutationFn = Apollo.MutationFunction<Delete_VokMutation, Delete_VokMutationVariables>;
/**
 * __useDelete_VokMutation__
 *
 * To run a mutation, you first call `useDelete_VokMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDelete_VokMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteVokMutation, { data, loading, error }] = useDelete_VokMutation({
 *   variables: {
 *      vokId: // value for 'vokId'
 *   },
 * });
 */
export declare function useDelete_VokMutation(baseOptions?: Apollo.MutationHookOptions<Delete_VokMutation, Delete_VokMutationVariables>): Apollo.MutationTuple<Delete_VokMutation, Exact<{
    vokId: any;
}>>;
export declare type Delete_VokMutationHookResult = ReturnType<typeof useDelete_VokMutation>;
export declare type Delete_VokMutationResult = Apollo.MutationResult<Delete_VokMutation>;
export declare type Delete_VokMutationOptions = Apollo.BaseMutationOptions<Delete_VokMutation, Delete_VokMutationVariables>;
