/* 5fe522fdc81af247339cb2aca2d711d7b2cfd671
 * This file is automatically generated by graphql-let. */

import * as Apollo from '@apollo/client';
export declare type Maybe<T> = T | null;
export declare type Exact<T extends {
    [key: string]: unknown;
}> = {
    [K in keyof T]: T[K];
};
export declare type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]?: Maybe<T[SubKey]>;
};
export declare type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]: Maybe<T[SubKey]>;
};
/** All built-in and custom scalars, mapped to their actual values */
export declare type Scalars = {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
    /** Mongo id scalar type */
    ObjectId: any;
};
export declare type LoginInput = {
    email: Scalars['String'];
    password: Scalars['String'];
};
export declare type Mutation = {
    __typename?: 'Mutation';
    createVoc: Vokabel;
    deleteVok: Scalars['Boolean'];
    login: UserResponse;
    register: UserResponse;
    udpateVok: Vokabel;
};
export declare type MutationCreateVocArgs = {
    input: VokabelInput;
};
export declare type MutationDeleteVokArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type MutationLoginArgs = {
    input: LoginInput;
};
export declare type MutationRegisterArgs = {
    input: RegisterInput;
};
export declare type MutationUdpateVokArgs = {
    input: VokabelInput;
};
export declare type Query = {
    __typename?: 'Query';
    getLoggedUser?: Maybe<User>;
    readUserVoks: Array<Vokabel>;
    readVoc: Vokabel;
    readVocs: Array<Vokabel>;
    user?: Maybe<User>;
};
export declare type QueryReadUserVoksArgs = {
    userId: Scalars['ObjectId'];
};
export declare type QueryReadVocArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type QueryUserArgs = {
    userId: Scalars['ObjectId'];
};
export declare type RegisterInput = {
    email: Scalars['String'];
    password: Scalars['String'];
    username: Scalars['String'];
};
/** User */
export declare type User = {
    __typename?: 'User';
    _id: Scalars['ObjectId'];
    email: Scalars['String'];
    username: Scalars['String'];
};
export declare type UserResponse = {
    __typename?: 'UserResponse';
    token?: Maybe<Scalars['String']>;
    user?: Maybe<User>;
};
/** Vokabel */
export declare type Vokabel = {
    __typename?: 'Vokabel';
    _id: Scalars['ObjectId'];
    creator: User;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type VokabelInput = {
    _id?: Maybe<Scalars['ObjectId']>;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type Read_VokQueryVariables = Exact<{
    vokId: Scalars['ObjectId'];
}>;
export declare type Read_VokQuery = ({
    __typename?: 'Query';
} & {
    readVoc: ({
        __typename?: 'Vokabel';
    } & Pick<Vokabel, '_id' | 'deutsch' | 'koreanisch'> & {
        creator: ({
            __typename?: 'User';
        } & Pick<User, '_id' | 'email' | 'username'>);
    });
});
export declare const Read_VokDocument: Apollo.DocumentNode;
/**
 * __useRead_VokQuery__
 *
 * To run a query within a React component, call `useRead_VokQuery` and pass it any options that fit your needs.
 * When your component renders, `useRead_VokQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useRead_VokQuery({
 *   variables: {
 *      vokId: // value for 'vokId'
 *   },
 * });
 */
export declare function useRead_VokQuery(baseOptions: Apollo.QueryHookOptions<Read_VokQuery, Read_VokQueryVariables>): Apollo.QueryResult<Read_VokQuery, Exact<{
    vokId: any;
}>>;
export declare function useRead_VokLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<Read_VokQuery, Read_VokQueryVariables>): Apollo.QueryTuple<Read_VokQuery, Exact<{
    vokId: any;
}>>;
export declare type Read_VokQueryHookResult = ReturnType<typeof useRead_VokQuery>;
export declare type Read_VokLazyQueryHookResult = ReturnType<typeof useRead_VokLazyQuery>;
export declare type Read_VokQueryResult = Apollo.QueryResult<Read_VokQuery, Read_VokQueryVariables>;
