/* 2dc11fcaef93bf360e365853c7d894869df302b6
 * This file is automatically generated by graphql-let. */

import * as Apollo from '@apollo/client';
export declare type Maybe<T> = T | null;
export declare type Exact<T extends {
    [key: string]: unknown;
}> = {
    [K in keyof T]: T[K];
};
export declare type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]?: Maybe<T[SubKey]>;
};
export declare type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]: Maybe<T[SubKey]>;
};
/** All built-in and custom scalars, mapped to their actual values */
export declare type Scalars = {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
    /** Mongo id scalar type */
    ObjectId: any;
};
export declare type LoginInput = {
    email: Scalars['String'];
    password: Scalars['String'];
};
export declare type Mutation = {
    __typename?: 'Mutation';
    createVoc: Vokabel;
    deleteVok: Scalars['Boolean'];
    login: UserResponse;
    register: UserResponse;
    udpateVok: Vokabel;
};
export declare type MutationCreateVocArgs = {
    input: VokabelInput;
};
export declare type MutationDeleteVokArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type MutationLoginArgs = {
    input: LoginInput;
};
export declare type MutationRegisterArgs = {
    input: RegisterInput;
};
export declare type MutationUdpateVokArgs = {
    input: VokabelInput;
};
export declare type Query = {
    __typename?: 'Query';
    getLoggedUser?: Maybe<User>;
    readUserVoks: Array<Vokabel>;
    readVoc: Vokabel;
    readVocs: Array<Vokabel>;
    user?: Maybe<User>;
};
export declare type QueryReadUserVoksArgs = {
    userId: Scalars['ObjectId'];
};
export declare type QueryReadVocArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type QueryUserArgs = {
    userId: Scalars['ObjectId'];
};
export declare type RegisterInput = {
    email: Scalars['String'];
    password: Scalars['String'];
    username: Scalars['String'];
};
/** User */
export declare type User = {
    __typename?: 'User';
    _id: Scalars['ObjectId'];
    email: Scalars['String'];
    username: Scalars['String'];
};
export declare type UserResponse = {
    __typename?: 'UserResponse';
    token?: Maybe<Scalars['String']>;
    user?: Maybe<User>;
};
/** Vokabel */
export declare type Vokabel = {
    __typename?: 'Vokabel';
    _id: Scalars['ObjectId'];
    creator: User;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type VokabelInput = {
    _id?: Maybe<Scalars['ObjectId']>;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type SigninMutationVariables = Exact<{
    email: Scalars['String'];
    password: Scalars['String'];
}>;
export declare type SigninMutation = ({
    __typename?: 'Mutation';
} & {
    login: ({
        __typename?: 'UserResponse';
    } & Pick<UserResponse, 'token'> & {
        user?: Maybe<({
            __typename?: 'User';
        } & Pick<User, '_id' | 'username' | 'email'>)>;
    });
});
export declare const SigninDocument: Apollo.DocumentNode;
export declare type SigninMutationFn = Apollo.MutationFunction<SigninMutation, SigninMutationVariables>;
/**
 * __useSigninMutation__
 *
 * To run a mutation, you first call `useSigninMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSigninMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [signinMutation, { data, loading, error }] = useSigninMutation({
 *   variables: {
 *      email: // value for 'email'
 *      password: // value for 'password'
 *   },
 * });
 */
export declare function useSigninMutation(baseOptions?: Apollo.MutationHookOptions<SigninMutation, SigninMutationVariables>): Apollo.MutationTuple<SigninMutation, Exact<{
    email: string;
    password: string;
}>>;
export declare type SigninMutationHookResult = ReturnType<typeof useSigninMutation>;
export declare type SigninMutationResult = Apollo.MutationResult<SigninMutation>;
export declare type SigninMutationOptions = Apollo.BaseMutationOptions<SigninMutation, SigninMutationVariables>;
