/* 7180149ed30edb4e7ceeeaf73558a44f63d4be52
 * This file is automatically generated by graphql-let. */

import * as Apollo from '@apollo/client';
export declare type Maybe<T> = T | null;
export declare type Exact<T extends {
    [key: string]: unknown;
}> = {
    [K in keyof T]: T[K];
};
export declare type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]?: Maybe<T[SubKey]>;
};
export declare type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
    [SubKey in K]: Maybe<T[SubKey]>;
};
/** All built-in and custom scalars, mapped to their actual values */
export declare type Scalars = {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
    /** Mongo id scalar type */
    ObjectId: any;
};
export declare type LoginInput = {
    email: Scalars['String'];
    password: Scalars['String'];
};
export declare type Mutation = {
    __typename?: 'Mutation';
    createVoc: Vokabel;
    deleteVok: Scalars['Boolean'];
    login: UserResponse;
    register: UserResponse;
    udpateVok: Vokabel;
};
export declare type MutationCreateVocArgs = {
    input: VokabelInput;
};
export declare type MutationDeleteVokArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type MutationLoginArgs = {
    input: LoginInput;
};
export declare type MutationRegisterArgs = {
    input: RegisterInput;
};
export declare type MutationUdpateVokArgs = {
    input: VokabelInput;
};
export declare type Query = {
    __typename?: 'Query';
    getLoggedUser?: Maybe<User>;
    readUserVoks: Array<Vokabel>;
    readVoc: Vokabel;
    readVocs: Array<Vokabel>;
    user?: Maybe<User>;
};
export declare type QueryReadUserVoksArgs = {
    userId: Scalars['ObjectId'];
};
export declare type QueryReadVocArgs = {
    vokId: Scalars['ObjectId'];
};
export declare type QueryUserArgs = {
    userId: Scalars['ObjectId'];
};
export declare type RegisterInput = {
    email: Scalars['String'];
    password: Scalars['String'];
    username: Scalars['String'];
};
/** User */
export declare type User = {
    __typename?: 'User';
    _id: Scalars['ObjectId'];
    email: Scalars['String'];
    username: Scalars['String'];
};
export declare type UserResponse = {
    __typename?: 'UserResponse';
    token?: Maybe<Scalars['String']>;
    user?: Maybe<User>;
};
/** Vokabel */
export declare type Vokabel = {
    __typename?: 'Vokabel';
    _id: Scalars['ObjectId'];
    creator: User;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type VokabelInput = {
    _id?: Maybe<Scalars['ObjectId']>;
    deutsch: Scalars['String'];
    koreanisch: Scalars['String'];
};
export declare type Update_VokMutationVariables = Exact<{
    input: VokabelInput;
}>;
export declare type Update_VokMutation = ({
    __typename?: 'Mutation';
} & {
    udpateVok: ({
        __typename?: 'Vokabel';
    } & Pick<Vokabel, '_id' | 'deutsch' | 'koreanisch'> & {
        creator: ({
            __typename?: 'User';
        } & Pick<User, '_id' | 'username' | 'email'>);
    });
});
export declare const Update_VokDocument: Apollo.DocumentNode;
export declare type Update_VokMutationFn = Apollo.MutationFunction<Update_VokMutation, Update_VokMutationVariables>;
/**
 * __useUpdate_VokMutation__
 *
 * To run a mutation, you first call `useUpdate_VokMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdate_VokMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateVokMutation, { data, loading, error }] = useUpdate_VokMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useUpdate_VokMutation(baseOptions?: Apollo.MutationHookOptions<Update_VokMutation, Update_VokMutationVariables>): Apollo.MutationTuple<Update_VokMutation, Exact<{
    input: VokabelInput;
}>>;
export declare type Update_VokMutationHookResult = ReturnType<typeof useUpdate_VokMutation>;
export declare type Update_VokMutationResult = Apollo.MutationResult<Update_VokMutation>;
export declare type Update_VokMutationOptions = Apollo.BaseMutationOptions<Update_VokMutation, Update_VokMutationVariables>;
