/* 3c9cbc114cd967a882d36190a6c554ca563a1f1b
 * This file is automatically generated by graphql-let. */

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** Mongo id scalar type */
  ObjectId: any;
};

export type LoginInput = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createVoc: Vokabel;
  deleteVok: Scalars['Boolean'];
  login: UserResponse;
  register: UserResponse;
  udpateVok: Vokabel;
};


export type MutationCreateVocArgs = {
  input: VokabelInput;
};


export type MutationDeleteVokArgs = {
  vokId: Scalars['ObjectId'];
};


export type MutationLoginArgs = {
  input: LoginInput;
};


export type MutationRegisterArgs = {
  input: RegisterInput;
};


export type MutationUdpateVokArgs = {
  input: VokabelInput;
};


export type Query = {
  __typename?: 'Query';
  getLoggedUser?: Maybe<User>;
  readUserVoks: Array<Vokabel>;
  readVoc: Vokabel;
  readVocs: Array<Vokabel>;
  user?: Maybe<User>;
};


export type QueryReadUserVoksArgs = {
  userId: Scalars['ObjectId'];
};


export type QueryReadVocArgs = {
  vokId: Scalars['ObjectId'];
};


export type QueryUserArgs = {
  userId: Scalars['ObjectId'];
};

export type RegisterInput = {
  email: Scalars['String'];
  password: Scalars['String'];
  username: Scalars['String'];
};

/** User */
export type User = {
  __typename?: 'User';
  _id: Scalars['ObjectId'];
  email: Scalars['String'];
  username: Scalars['String'];
};

export type UserResponse = {
  __typename?: 'UserResponse';
  token?: Maybe<Scalars['String']>;
  user?: Maybe<User>;
};

/** Vokabel */
export type Vokabel = {
  __typename?: 'Vokabel';
  _id: Scalars['ObjectId'];
  creator: User;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type VokabelInput = {
  _id?: Maybe<Scalars['ObjectId']>;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type Create_VokMutationVariables = Exact<{
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
}>;


export type Create_VokMutation = (
  { __typename?: 'Mutation' }
  & { createVoc: (
    { __typename?: 'Vokabel' }
    & Pick<Vokabel, '_id' | 'koreanisch' | 'deutsch'>
    & { creator: (
      { __typename?: 'User' }
      & Pick<User, '_id' | 'username' | 'email'>
    ) }
  ) }
);


export const Create_VokDocument = gql`
    mutation CREATE_VOK($deutsch: String!, $koreanisch: String!) {
  createVoc(input: {deutsch: $deutsch, koreanisch: $koreanisch}) {
    _id
    koreanisch
    deutsch
    creator {
      _id
      username
      email
    }
  }
}
    `;
export type Create_VokMutationFn = Apollo.MutationFunction<Create_VokMutation, Create_VokMutationVariables>;

/**
 * __useCreate_VokMutation__
 *
 * To run a mutation, you first call `useCreate_VokMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreate_VokMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createVokMutation, { data, loading, error }] = useCreate_VokMutation({
 *   variables: {
 *      deutsch: // value for 'deutsch'
 *      koreanisch: // value for 'koreanisch'
 *   },
 * });
 */
export function useCreate_VokMutation(baseOptions?: Apollo.MutationHookOptions<Create_VokMutation, Create_VokMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<Create_VokMutation, Create_VokMutationVariables>(Create_VokDocument, options);
      }
export type Create_VokMutationHookResult = ReturnType<typeof useCreate_VokMutation>;
export type Create_VokMutationResult = Apollo.MutationResult<Create_VokMutation>;
export type Create_VokMutationOptions = Apollo.BaseMutationOptions<Create_VokMutation, Create_VokMutationVariables>;