/* e1a15a0dbb0050b3b56229b75c24432324cdf0cd
 * This file is automatically generated by graphql-let. */

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** Mongo id scalar type */
  ObjectId: any;
};

export type LoginInput = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createVoc: Vokabel;
  deleteVok: Scalars['Boolean'];
  login: UserResponse;
  register: UserResponse;
  udpateVok: Vokabel;
};


export type MutationCreateVocArgs = {
  input: VokabelInput;
};


export type MutationDeleteVokArgs = {
  vokId: Scalars['ObjectId'];
};


export type MutationLoginArgs = {
  input: LoginInput;
};


export type MutationRegisterArgs = {
  input: RegisterInput;
};


export type MutationUdpateVokArgs = {
  input: VokabelInput;
};


export type Query = {
  __typename?: 'Query';
  getLoggedUser?: Maybe<User>;
  readUserVoks: Array<Vokabel>;
  readVoc: Vokabel;
  readVocs: Array<Vokabel>;
  user?: Maybe<User>;
};


export type QueryReadUserVoksArgs = {
  userId: Scalars['ObjectId'];
};


export type QueryReadVocArgs = {
  vokId: Scalars['ObjectId'];
};


export type QueryUserArgs = {
  userId: Scalars['ObjectId'];
};

export type RegisterInput = {
  email: Scalars['String'];
  password: Scalars['String'];
  username: Scalars['String'];
};

/** User */
export type User = {
  __typename?: 'User';
  _id: Scalars['ObjectId'];
  email: Scalars['String'];
  username: Scalars['String'];
};

export type UserResponse = {
  __typename?: 'UserResponse';
  token?: Maybe<Scalars['String']>;
  user?: Maybe<User>;
};

/** Vokabel */
export type Vokabel = {
  __typename?: 'Vokabel';
  _id: Scalars['ObjectId'];
  creator: User;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type VokabelInput = {
  _id?: Maybe<Scalars['ObjectId']>;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type Delete_VokMutationVariables = Exact<{
  vokId: Scalars['ObjectId'];
}>;


export type Delete_VokMutation = (
  { __typename?: 'Mutation' }
  & Pick<Mutation, 'deleteVok'>
);


export const Delete_VokDocument = gql`
    mutation DELETE_VOK($vokId: ObjectId!) {
  deleteVok(vokId: $vokId)
}
    `;
export type Delete_VokMutationFn = Apollo.MutationFunction<Delete_VokMutation, Delete_VokMutationVariables>;

/**
 * __useDelete_VokMutation__
 *
 * To run a mutation, you first call `useDelete_VokMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDelete_VokMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteVokMutation, { data, loading, error }] = useDelete_VokMutation({
 *   variables: {
 *      vokId: // value for 'vokId'
 *   },
 * });
 */
export function useDelete_VokMutation(baseOptions?: Apollo.MutationHookOptions<Delete_VokMutation, Delete_VokMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<Delete_VokMutation, Delete_VokMutationVariables>(Delete_VokDocument, options);
      }
export type Delete_VokMutationHookResult = ReturnType<typeof useDelete_VokMutation>;
export type Delete_VokMutationResult = Apollo.MutationResult<Delete_VokMutation>;
export type Delete_VokMutationOptions = Apollo.BaseMutationOptions<Delete_VokMutation, Delete_VokMutationVariables>;