/* 2a6555e28405450ac5b110842a055f1154f98bbb
 * This file is automatically generated by graphql-let. */

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** Mongo id scalar type */
  ObjectId: any;
};

export type LoginInput = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createVoc: Vokabel;
  deleteVok: Scalars['Boolean'];
  login: UserResponse;
  register: UserResponse;
  udpateVok: Vokabel;
};


export type MutationCreateVocArgs = {
  input: VokabelInput;
};


export type MutationDeleteVokArgs = {
  vokId: Scalars['ObjectId'];
};


export type MutationLoginArgs = {
  input: LoginInput;
};


export type MutationRegisterArgs = {
  input: RegisterInput;
};


export type MutationUdpateVokArgs = {
  input: VokabelInput;
};


export type Query = {
  __typename?: 'Query';
  getLoggedUser?: Maybe<User>;
  readUserVoks: Array<Vokabel>;
  readVoc: Vokabel;
  readVocs: Array<Vokabel>;
  user?: Maybe<User>;
};


export type QueryReadUserVoksArgs = {
  userId: Scalars['ObjectId'];
};


export type QueryReadVocArgs = {
  vokId: Scalars['ObjectId'];
};


export type QueryUserArgs = {
  userId: Scalars['ObjectId'];
};

export type RegisterInput = {
  email: Scalars['String'];
  password: Scalars['String'];
  username: Scalars['String'];
};

/** User */
export type User = {
  __typename?: 'User';
  _id: Scalars['ObjectId'];
  email: Scalars['String'];
  username: Scalars['String'];
};

export type UserResponse = {
  __typename?: 'UserResponse';
  token?: Maybe<Scalars['String']>;
  user?: Maybe<User>;
};

/** Vokabel */
export type Vokabel = {
  __typename?: 'Vokabel';
  _id: Scalars['ObjectId'];
  creator: User;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type VokabelInput = {
  _id?: Maybe<Scalars['ObjectId']>;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type Logged_In_UserQueryVariables = Exact<{ [key: string]: never; }>;


export type Logged_In_UserQuery = (
  { __typename?: 'Query' }
  & { getLoggedUser?: Maybe<(
    { __typename?: 'User' }
    & Pick<User, '_id' | 'email' | 'username'>
  )> }
);


export const Logged_In_UserDocument = gql`
    query LOGGED_IN_USER {
  getLoggedUser {
    _id
    email
    username
  }
}
    `;

/**
 * __useLogged_In_UserQuery__
 *
 * To run a query within a React component, call `useLogged_In_UserQuery` and pass it any options that fit your needs.
 * When your component renders, `useLogged_In_UserQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useLogged_In_UserQuery({
 *   variables: {
 *   },
 * });
 */
export function useLogged_In_UserQuery(baseOptions?: Apollo.QueryHookOptions<Logged_In_UserQuery, Logged_In_UserQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<Logged_In_UserQuery, Logged_In_UserQueryVariables>(Logged_In_UserDocument, options);
      }
export function useLogged_In_UserLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<Logged_In_UserQuery, Logged_In_UserQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<Logged_In_UserQuery, Logged_In_UserQueryVariables>(Logged_In_UserDocument, options);
        }
export type Logged_In_UserQueryHookResult = ReturnType<typeof useLogged_In_UserQuery>;
export type Logged_In_UserLazyQueryHookResult = ReturnType<typeof useLogged_In_UserLazyQuery>;
export type Logged_In_UserQueryResult = Apollo.QueryResult<Logged_In_UserQuery, Logged_In_UserQueryVariables>;