/* 5fe522fdc81af247339cb2aca2d711d7b2cfd671
 * This file is automatically generated by graphql-let. */

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** Mongo id scalar type */
  ObjectId: any;
};

export type LoginInput = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createVoc: Vokabel;
  deleteVok: Scalars['Boolean'];
  login: UserResponse;
  register: UserResponse;
  udpateVok: Vokabel;
};


export type MutationCreateVocArgs = {
  input: VokabelInput;
};


export type MutationDeleteVokArgs = {
  vokId: Scalars['ObjectId'];
};


export type MutationLoginArgs = {
  input: LoginInput;
};


export type MutationRegisterArgs = {
  input: RegisterInput;
};


export type MutationUdpateVokArgs = {
  input: VokabelInput;
};


export type Query = {
  __typename?: 'Query';
  getLoggedUser?: Maybe<User>;
  readUserVoks: Array<Vokabel>;
  readVoc: Vokabel;
  readVocs: Array<Vokabel>;
  user?: Maybe<User>;
};


export type QueryReadUserVoksArgs = {
  userId: Scalars['ObjectId'];
};


export type QueryReadVocArgs = {
  vokId: Scalars['ObjectId'];
};


export type QueryUserArgs = {
  userId: Scalars['ObjectId'];
};

export type RegisterInput = {
  email: Scalars['String'];
  password: Scalars['String'];
  username: Scalars['String'];
};

/** User */
export type User = {
  __typename?: 'User';
  _id: Scalars['ObjectId'];
  email: Scalars['String'];
  username: Scalars['String'];
};

export type UserResponse = {
  __typename?: 'UserResponse';
  token?: Maybe<Scalars['String']>;
  user?: Maybe<User>;
};

/** Vokabel */
export type Vokabel = {
  __typename?: 'Vokabel';
  _id: Scalars['ObjectId'];
  creator: User;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type VokabelInput = {
  _id?: Maybe<Scalars['ObjectId']>;
  deutsch: Scalars['String'];
  koreanisch: Scalars['String'];
};

export type Read_VokQueryVariables = Exact<{
  vokId: Scalars['ObjectId'];
}>;


export type Read_VokQuery = (
  { __typename?: 'Query' }
  & { readVoc: (
    { __typename?: 'Vokabel' }
    & Pick<Vokabel, '_id' | 'deutsch' | 'koreanisch'>
    & { creator: (
      { __typename?: 'User' }
      & Pick<User, '_id' | 'email' | 'username'>
    ) }
  ) }
);


export const Read_VokDocument = gql`
    query READ_VOK($vokId: ObjectId!) {
  readVoc(vokId: $vokId) {
    _id
    deutsch
    koreanisch
    creator {
      _id
      email
      username
    }
  }
}
    `;

/**
 * __useRead_VokQuery__
 *
 * To run a query within a React component, call `useRead_VokQuery` and pass it any options that fit your needs.
 * When your component renders, `useRead_VokQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useRead_VokQuery({
 *   variables: {
 *      vokId: // value for 'vokId'
 *   },
 * });
 */
export function useRead_VokQuery(baseOptions: Apollo.QueryHookOptions<Read_VokQuery, Read_VokQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<Read_VokQuery, Read_VokQueryVariables>(Read_VokDocument, options);
      }
export function useRead_VokLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<Read_VokQuery, Read_VokQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<Read_VokQuery, Read_VokQueryVariables>(Read_VokDocument, options);
        }
export type Read_VokQueryHookResult = ReturnType<typeof useRead_VokQuery>;
export type Read_VokLazyQueryHookResult = ReturnType<typeof useRead_VokLazyQuery>;
export type Read_VokQueryResult = Apollo.QueryResult<Read_VokQuery, Read_VokQueryVariables>;